### ISSUE TITLE
Ensure MVP functionality for client deployment of managed grafana

### ISSUE THREAD

**Issue by PaulHLiatrio** [liatrio/aws-managed-services#9]
# Overview
We need to ensure a basic set of MVP functionality for client deployments within enteprises

## Acceptance Criteria
* documentation is updated where applicable
* grafana is deployable with SAML 
* feature flags are available 
* grafana is connected via private network (tailscale or other vpn solutions)

```[tasklist]
### Tasks
- [x] SAML is supported and can be disabled or enabled through feature flags
- [x] AMG can be connected to a private network (outbound and inbound)
- [x] Documentation in read me is updated
- [x] Documentation is projecto11y repo is updated
- [ ] Tailscale is deployed somewhere to confirm network connectivity
- [x] Ensure tags can be set
```
